item.10101=minecraft:torch minecraft:lantern minecraft:glowstone minecraft:campfire
item.10102=minecraft:soul_torch minecraft:soul_lantern minecraft:soul_campfire
item.10103=minecraft:lava_bucket minecraft:magma_block
item.10104=minecraft:redstone_torch
item.10105=minecraft:sea_lantern minecraft:end_rod minecraft:beacon
item.10106=minecraft:end_crystal
